### ISSUE TITLE
strstr takes array as 1st argument

### ISSUE THREAD

**Issue by inpos** [dim-0/ldapAliasSync#13]
Hi!
I think there must be 
`$login['local'] = $login['login'];`
at line # 146 in ldapAliasSync.php

**Comment by dim-0** [comment]
Hi inpos,

thanks for pointing this out. I'm sorry for letting you wait for so long, but I'm currently on a long term travel, so things take a while :)
I don't think the way it was before didn't break anything (corresponding to the way php handles arrays), nevertheless the way it is now is cleaner.

Cheers!
