### ISSUE TITLE
Make this plugin available via RC's plugin repository

### ISSUE THREAD

**Issue by dim-0** [dim-0/ldapAliasSync#4]
The plugin should be made available via RC's plugin repository using the composer framework (see http://plugins.roundcube.net/)

**Comment by thawy-dev** [comment]
Hello guys!
Thank a lot for beautiful plugin!
can you help me with build correct filter for Active Directory,
i download latest version of olugin from this repo
so, i was configured plugin correctly, but have an error in log file:

User 'r.terekhov@synevo.ua' not found (pass 1). Filter: (&(userprincipalname=r.terekhov@synevo.ua)(useraccountcontrol:1.2.840.113556.1.4.803:=512)(!(useraccountcontrol:1.2.840.113556.1.4.803:=2)))

although, if i use same filter in LdapAdmin - i can fetch a result user from ldap.

its my config:

'ldap' => array(
        # LDAP server address (required)
        'server'     => 'ldap://myserver',

        # LDAP Bind DN (requried, if no anonymous read rights are set for the accounts)
        'bind_dn'    => 'ldapaccess@myserver',

        # Bind password (required, if the bind DN needs to authenticate)
        'bind_pw'    => 'password',

        # LDAP search base (required)
        'base_dn'    => 'dc=mydomain,dc=myzone',

        # LDAP search filter (required)
        # This open filter possibility is the heart of the LDAP search.
        # - Use '%login' as a place holder for the login name
        # - Use '%local' as a place holder for the login name local part
        # - Use '%domain' as a place holder for the login name domain part (/'search_domain', if not given or replaced)
        # - Use '%email' as a place holder for the email address ('%local'@'%domain')
        # However, remember to search for the original entry, too (e.g. 'uid=%1$s'), as this is an identity as well!
         'filter' => '(&(userprincipalname=%login)(useraccountcontrol:1.2.840.113556.1.4.803:=512)(!(useraccountcontrol:1.2.840.113556.1.4.803:=2)))',


        # LDAP email attribute (required)
        # If only the local part is returned, the 'find_domain' is appended (e.g. uid=asdf --> asdf@example.com).
        # If no domain part is returned and no 'find_domain' is given, the identity will not be fetched!
        'attr_mail'  => 'mail',

        # LDAP name attribute (optional)
        'attr_name'  => 'cn',

        # LDAP organization attribute (optional)
        'attr_org'   => 'company',


Thank a lot for any suggestions))

**Comment by dim-0** [comment]
Hi,

I don't think, that this is the right thread for your problem, as this issue is used for the composer framework integration (http://plugins.roundcube.net/) for this plugin. So if there is any update on this, please open up a new thread.

However, let me give some small suggestions anyway (they cannot be more than suggestions, because I never tested this repository in combination with AD).
What I see is that you use '%login' for the search filter. Are you sure, this is the right attribute? '%login' will be replaced with the login name. So if you use 'r.terekhov@synevo.ua' as the login name, the plugin will look for 'r.terekhov@synevo.ua'; if you use 'r.terekhov' instead, then this will be the search string. Maybe (depending on your setup) what you are looking for is the parameter '%local' because it will look for 'r.terekhov' in both cases. Of course this information is obsolete, if 'userprincipalname' will hold the e-mail address in your setup.
A second thing I see is the second half of your filter string. Your string looks like this:
(&(condition 1)(condition 2)(!(condition 3)))
For openLDAP (which I use) the exclamation mark is used as the 'OR' operator, the ampersand is used as the 'AND' operator. So the first ampersand will hold condition 1, condition 2 and the third part, where the 'OR' includes only one condition (like saying 'either condition 3' without any 'or condition 4'). Are you sure that this is correct? To me it looks a little bit like you wanted to negate condition 3, but I think this isn't the right way to do it.

Well, maybe my thoughts can help you somehow. If they don't, please create another issue and I will try to solve your problem there :)

Cheers,
dim-0

**Comment by dim-0** [comment]
Thanks to @yakatz this is finally done ;)
